### ISSUE TITLE
Updated to 2.0, but nothing is working

### ISSUE THREAD

**Issue by ArtOfficialIntelligence** [ni554n/redium#1]
Google cache - "404. That’s an error"

12ft - just shows all the text from the preview

Scribe - just shows all the text from the preview

LibMedium - "This libmedium.batsense.net page can’t be found"

**Comment by ni554n** [comment]
Please checkout the [changelog](https://github.com/ni554n/redium#changelog) as I've already written about this issue.

As this extension doesn't process any articles, if it is not working after redirecting, there's nothing I can do from my end unfortunately.

But you can paste the article links that are showing up as 404 on Google Cache, so that I can verify if it is really in cache or not.
